---
development:
  dialect: postgres
  database: {{envOr "POSTGRES_DB" ""}}
  user: {{envOr "POSTGRES_USER" ""}}
  password: {{envOr "POSTGRES_PASSWORD" ""}}
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" ""}}

production:
  url: {{envOr "DATABASE_URL" ""}}
